### ISSUE TITLE
[Exporter] NRF52_DK uvision5 is not supported

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/oob-mbed-os-example-blinky#3]
```
$ mbed export -m NRF52_DK -i uvision5

(snip)

Traceback (most recent call last):
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project.py", line 234, in <module>
    main()
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project.py", line 230, in main
    zip_proj=zip_proj, build_profile=profile)
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project.py", line 93, in export
    build_profile=build_profile, silent=silent)
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project_api.py", line 228, in export_project
    macros=macros)
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project_api.py", line 89, in generate_project_files
    exporter.generate()
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\export\uvision5.py", line 59, in generate
    project_data = self.progen_get_project_data()
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\export\exporters.py", line 122, in progen_get_project_data
    raise TargetNotSupportedException("Target not supported")
tools.export.exporters.TargetNotSupportedException: Target not supported
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project.py -i uvision5 -m NRF52_DK --source ." in "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky"
---
```

**Comment by MarceloSalazar** [comment]
To be tested in RC4

**Comment by toyowata** [comment]
Tested and confirmed the fix in RC4.
