### ISSUE TITLE
[Exporter] NRF52_DK IAR is not supported 

### ISSUE THREAD

**Issue by toyowata** [ARMmbed/oob-mbed-os-example-blinky#4]
```
$ mbed export -m NRF52_DK -i IAR

(snip)

Traceback (most recent call last):
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project.py", line 234, in <module>
    main()
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project.py", line 230, in main
    zip_proj=zip_proj, build_profile=profile)
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project.py", line 93, in export
    build_profile=build_profile, silent=silent)
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project_api.py", line 228, in export_project
    macros=macros)
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project_api.py", line 89, in generate_project_files
    exporter.generate()
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\export\iar.py", line 55, in generate
    project_data = self.progen_get_project_data()
  File "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\export\exporters.py", line 122, in progen_get_project_data
    raise TargetNotSupportedException("Target not supported")
tools.export.exporters.TargetNotSupportedException: Target not supported
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky\mbed-os\tools\project.py -i iar -m NRF52_DK --source ." in "C:\Users\toywat01\Documents\GitHub\oob-mbed-os-example-blinky"
---
```

**Comment by ashok-rao** [comment]
Issue still persists with RC2. Platform support needs to be added for IAR.

![nrf52_iar_export_error](https://cloud.githubusercontent.com/assets/17567812/19277175/bdebf64e-8fd0-11e6-8888-177e8376b4e1.jpg)

**Comment by ashok-rao** [comment]
Issue resolved. Closing. Thank you.
